# Generated by Django 2.1.2 on 2018-10-27 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=80, verbose_name='company')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('sm8_uuid', models.CharField(blank=True, max_length=80, verbose_name='sm8 uuid')),
                ('access_token', models.CharField(max_length=80, verbose_name='Access token')),
                ('refresh_token', models.CharField(max_length=80, verbose_name='Refresh token')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
